### ISSUE TITLE
How about hierarchical table structure

### ISSUE THREAD

**Issue by bharatpatil** [NeXTs/Clusterize.js#67] opened 2016-06-21 11:26 UTC
Will this work for hierarchical table structure which offers collapse and expand?

**Comment by NeXTs** [comment] 2016-06-21 11:33
Hi
I need some examples of your hierarchical structure
There are cool project with "collapse and expand" functionality based on div's. Table structure may be implemented in same manner

**Comment by bharatpatil** [comment] 2016-06-21 11:56
I'm currently using fancytree with it's table extension. You can find example here:
http://wwwendt.de/tech/fancytree/demo/index.html#sample-ext-table.html

**Comment by NeXTs** [comment] 2016-06-21 12:00
Oops, my fault, forgot to add links
take a look http://cheton.github.io/infinite-tree/examples.html#/filebrowser

**Comment by NeXTs** [comment] 2016-06-28 09:52
How it's going?

**Comment by bharatpatil** [comment] 2016-06-28 10:06
Currently exploring how that can be integrated with fancytree

**Comment by bharatpatil** [comment] 2016-07-03 14:24
@NeXTs - sorry for my less knowledge, this might be a very silly question, however I would like to know, why `fetchMarkup()` does not return original DOM elements, instead of returning outerHTML?

**Comment by NeXTs** [comment] 2016-07-03 14:32
@bharatpatil `fetchMarkup` function was designed for internal use only.
`outerHTML` needed because clusterize works with strings rather than DOM elements

**Comment by bharatpatil** [comment] 2016-07-03 14:46
@NeXTs - I've modified it to work with actual DOM elements, because I want that to work with [Fancytree](https://github.com/mar10/fancytree) because it has data associated with DOM elements and I'm very thankful to this wonderful library, it is handling 110160 nodes without any problem. 

Though the new change made is maintaining one more array of actual DOM nodes, in addition to `rows`. I may have to consider some improvements memory wise because now if I open task manager of Chrome it is consuming 1.2 GB of Memory.

**Comment by NeXTs** [comment] 2016-07-07 22:05
**1.2 GB of Memory** :open_mouth: 
Not sure this may be solved (if you want to actually store all DOM nodes in memory)

**Comment by NeXTs** [comment] 2016-07-15 14:37
@bharatpatil Do you still have some questions or we can close this issue?

**Comment by bharatpatil** [comment] 2016-07-15 14:56
Can close it. 





On Fri, Jul 15, 2016 at 8:07 PM +0530, "Denis Lukov" <notifications@github.com> wrote:












@bharatpatil Do you still have some questions or we can close this issue?

**Closed** 2016-07-15 14:57 UTC
