### ISSUE TITLE
Scrolling on OS X 10.x stops scrolling inside scroll area when viewing next chunk

### ISSUE THREAD

**Issue by mikelittman** [NeXTs/Clusterize.js#3] opened 2015-04-28 18:24 UTC
It appears that the scroll handoff between clusters inside a large list causes some problems with OS X smooth scrolling. See video: http://d.pr/v/1fQ67

**Comment by klihelp** [comment] 2015-04-29 00:25
Same happening for me too, tested on OSX Chrome.
I scrolled with touchpad to the bottom of the container quite fast; it's works if you scroll slower

**Comment by abacaj** [comment] 2015-04-29 04:45
Same here.

**Comment by NeXTs** [comment] 2015-04-29 18:55
Thanks for the feedback. I'm working on it.
I believe this happens when new cluster inserts to DOM, so as temporary workaround you could increase rows_in_block. In demo page it's specified about 25 everywhere, so you could try to set it 100. In total your table would contain 400 DOM elements, which anyway is better than 10000.

You could change that option in playground http://nexts.github.io/Clusterize.js/#playground

**Comment by mathieudutour** [comment] 2015-04-30 14:07
Same happening when rows_in_block pushed to 100

**Comment by cameron** [comment] 2015-05-02 19:15
Same thing here. Great demo, btw!

**Comment by tomasdev** [comment] 2015-05-04 13:51
Yeah, depending on `rows_in_block` it will allow you to keep finger/wheel scrolling a bit more or less. I think the best fix for it (meaning not to have this bug even when doing a crazy-fast-as-flash scroll), is to use a library like iscroll or similar to overwrite the native scrolling.

**Comment by kpowick** [comment] 2015-05-04 18:39
I'm seeing the same on OSX with inertial scrolling of the trackpad.  However, using the scrollbar itself and dragging it up/down does not cause the problem - Even when dragging the scrollbar much faster than inertial scrolling of the trackpad.  I suppose this is due to mouse pointer being "anchored" to the scrollbar control by its "mouse button down" event.

**Comment by MauricioKruijer** [comment] 2015-05-06 15:01
I do experience the same thing. It's a lot less when you set the `rows_in_block` to 200 but then it's starting to lag...
The demo is awesome :)

**Comment by as-com** [comment] 2015-05-14 03:04
This might be related to #11 on other devices.

**Comment by skitiz** [comment] 2015-05-27 05:19
I concur. While scrolling through lists, it jumps to the page scroll instead.

**Comment by NeXTs** [comment] 2015-08-05 11:45
@mikelittman @klihelp @abacaj @mathieudutour @cameron @tomasdev @kpowick @skitiz

Hello guys, please check if last commit (v0.10.0) helps.
Solution is a little bit crazy but it works in Chrome, as for me.
I'm still experiencing this issue with Safari on Mac, because Safari doesn't apply style that added before scrolling. It apply style when scrolling completes. I've tried various tricks to force Safari to redraw/repaint style, but without luck. Need some time for investigation.

Btw, someone please check other browsers on Mac.

**Comment by mathieudutour** [comment] 2015-08-05 11:55
Working in chrome 45, firefox 37 and Safari 9

**Comment by kpowick** [comment] 2015-08-10 02:31
Latest Chrome on OS X 10.10.4 is much better, though using the scrollbar still results in a smoother experience than inertial scrolling of the trackpad.  Safari (8.0.7) still exhibits some "jerkiness" or temporary freezing of the scrolling list when using the trackpad.  Using the scrollbar is ok.

**Comment by OscarGodson** [comment] 2015-11-30 20:01
Yeah, in Safari scrolling locks up in Safari 9 for me too still. Has there been any progress on this or maybe a commit in a branch we can test?

Happens in the demos and in my own implementation I'm resizing other elements on the page based on the `td` widths whenever the clusters update and when it locks up it it makes the other elements to resize incorrectly by a lot.

**Comment by as-com** [comment] 2015-11-30 20:13
There's also a strange issue about scrolling by dragging the scrollbar around in Safari 9.0.1: https://cloudup.com/cFkhiYqEuKT

**Comment by NeXTs** [comment] 2015-12-02 11:38
@OscarGodson Unfortunately I have no my own Mac yet so I can not dive into it completely.
@as-com Could you please provide some simplified codepen/jsfiddle example?

**Comment by vamp** [comment] 2015-12-10 11:48
@as-com, yep, just becase clusterize (scrollEv) needs to be added to "wheel" event (for scrollElement & document) and looks like it solves this issue.

**Comment by NeXTs** [comment] 2016-12-20 10:38
@vamp I want keep scrolling native

**Comment by NeXTs** [comment] 2016-12-20 10:43
Finally I got Mac with OS X v10.11.6
Can't reproduce this problem anymore. Works as expected in Chrome 55.0.2883.95, Safari 10.0.2, Firefox 50.1.0

Does someone still experience this problem?
If not I'll close this issue in one month.

**Closed** 2017-02-06 13:05 UTC
Labels: bug
