### ISSUE TITLE
Only able to see first cluster (Node.js)

### ISSUE THREAD

**Issue by ioncloud64** [NeXTs/Clusterize.js#167] opened 2019-05-22 15:25 UTC
Hi,

I hope someone will be able to shed some light upon my issue. I've seen countless times the other closed issues of Clusterize.js where people have had the same problem. I've cross-referenced my application and haven't had any success in finding out where my issue lies.

Here's the issue I'm having
![error](https://user-images.githubusercontent.com/7088450/58186598-d2713680-7c7a-11e9-8c83-c52e99abd471.gif)

As you can see, I'm having issues with the rest of the list being blank, even though there is data left.

I've checked my styles, they're loading correctly.
![image](https://user-images.githubusercontent.com/7088450/58186849-4d3a5180-7c7b-11e9-9483-ad241f160bdb.png)

I included a screenshot of what the data being passed consists of, and I also tried showing the source with styles correctly loading.

I'm using Node.js v8.10.0, Electron (for UI), and Clusterize.js v0.18.1 from npm.

**Comment by NeXTs** [comment] 2019-05-22 19:08
Hello
Could you provide demo on codepen?

**Comment by ioncloud64** [comment] 2019-05-22 21:28
I can try to mock something up. I'll also post a link to the repo I have it in

**Comment by MarkWissler** [comment] 2019-05-23 22:22
Hi all. I'm having the same issue. I made a codepen here: https://codepen.io/markwissler/pen/byLXeY

I may be missing something, but my general html structure is reflected here. Thanks in advance.

**Comment by ioncloud64** [comment] 2019-05-23 23:51
Thanks for your codepen. I've been a little busy with other work to come up with something similar, but I see that yours has the same issue going on.

**Comment by ioncloud64** [comment] 2019-05-23 23:55
Here's my specific case of the HTML that's causing me issues. https://github.com/ioncloud64/freemegb/blob/master/main.html

**Comment by MarkWissler** [comment] 2019-06-04 15:05
@ioncloud64 my instance was fixed by checking out the `.scrollTop` of the element I was scrolling. In my codepen, if you just set the CSS class selector from contentArea to scrollArea (such that clusterize is reading the scrolling properly: from scrollArea, not contentArea) then it works. That may or may not be the same issue you're seeing, but it's worth a shot. To debug that this was the cause, I put in a `setTimeout(function () { console.log(clusterize.getScrollProgress()); }, 3000)` and scrolled as far down as I could, and still saw `0` as the scroll progress.

**Comment by ioncloud64** [comment] 2019-06-04 17:44
@MarkWissler interesting. I forked your codepen and made the changes you suggested. It worked. So then, I changed both of the scrollId and contentId to contentArea and that worked. So what I'm thinking is, scrollId/contentId have to be the same in order for it to work. I'll test performance out in a few minutes.

**Comment by MarkWissler** [comment] 2019-06-04 17:54
I did the same thing in my real application, which seemed to work. I started to run into stuttering, which I'm unsure how to resolve since in my case, the div I need to scroll is nested inside another scrollable div, so scrapping the effort for now.

**Comment by ioncloud64** [comment] 2019-06-04 18:31
I tried to apply the fix in my Node.js application and it did not work. It appears that when setting scrollArea to both, it breaks the code. When applying contentArea, it only loads one full cluster. With my data, I have probably 30 clusters that need to be shown.

**Comment by MarkWissler** [comment] 2019-06-04 18:43
Same for mine. I have ~12 clusters of 30-1100 items each. What happened when you set the content area and scroll area to be the same?

**Comment by ioncloud64** [comment] 2019-06-05 05:03
It only loaded 1 cluster. It turned blank way earlier than the previous version. I highly doubt it's an issue with memory. I'm running it on 32GB of RAM. If you want I can post a file with the table in question

**Comment by ioncloud64** [comment] 2019-06-05 14:49
I believe I may have found an issue with my application. I believe it's because of the event listener I'm using. I'll try to make Clusterize local to the page, then add it via event listener.

**Comment by ioncloud64** [comment] 2019-06-05 15:23
Tried to make it page-local, same results still.

**Comment by ioncloud64** [comment] 2019-06-19 02:56
Any update @NeXTs ? @MarkWissler

**Comment by MarkWissler** [comment] 2019-06-19 13:39
None from me, I gave up on it. The jittery scrolling was too much.

**Comment by ioncloud64** [comment] 2019-06-21 04:18
@MarkWissler got an alternative? I have so much data I can't possible load it all natively w/ HTML.

**Comment by ioncloud64** [comment] 2019-06-27 23:05
@MarkWissler I found an alternative. It's called slickgrid. You can install it via npm but you'll need to link to the javascript and jquery libraries individually. I'll post a link with my updated source code and comments of changes.

**Closed** 2019-07-08 17:32 UTC
